<?php

use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function simple_batch_node_insert(NodeInterface $node) {
  $data['title'] = $node->label();
  $data['time'] = $node->getCreatedTime();
  $data['link'] = $node->toLink()->toString();
  $queue = \Drupal::queue('my_custom_email');
  $queue->createQueue();
  $queue->createItem([
    'node_title' => $data['title'],
    'node_time' => $data['time'],
    'node_link' => $data['link'],
  ]);
}
